name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: v1.24.1
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Unit tests
        run: go test $(go list ./... | grep -v /go-graceful-shutdown/)
      - name: Acceptance tests
        run: go test $(go list ./... | grep go-graceful-shutdown)
